#%RAML 1.0

##
# API INFORMATION
##
title: Weather Hub
mediaType: application/json
baseUri: http:localhost:8080/api

##
# RESOURCE TYPES
##
types:

  ##
  # NODE
  ##
  Node:
    properties:
      id:
        type: string
        description: ID of the node
      name:
        type: string
        description: Name of the node
      address:
        type: string
        description: Ip-address of the node
      online:
        type: boolean
        description: True if the node is currently online

  ##
  # HUMIDITY
  ##
  Humidity:
    properties:
      timestamp:
        type: number
        description: Timestamp of the reading
        required: false
      value:
        type: number
        description: The humidity value
        required: true

  ##
  # TEMPERATURE
  ##
  Temperature:
    properties:
      timestamp:
        type: number
        description: Timestamp of the reading
        required: false
      value:
        type: number
        description: Temperature value
        required: true

  ##
  # LATEST
  ##
  Latest:
    properties:
      temperature:
        type: Temperature
        description: Latest entry for the temperature
      humidity:
        type: Humidity
        description: Latest entry for the humidity

##
# ROUTES
##
/nodes:
  get:
    responses:
      200:
        body:
          type: array
          items: Node

/nodes/{nodeId}:
  get:
  put:
    responses:
      200:
        body:
          type: Node

/nodes/{nodeId}/latest:
  get:
    responses:
      200:
        body:
          type: Latest

/nodes/{nodeId}/latest/temperature:
  get:
  put:
    responses:
      200:
        body:
          type: Temperature

/nodes/{nodeId}/latest/humidity:
  get:
  put:
    responses:
      200:
        body:
          type: Humidity
